"""
URL Attribution Engine — Forensic HAR Analysis
===============================================
Extracts, classifies, and attributes every URL involved in an LLM workflow
to one of three forensic categories:

    HUMAN    — URLs initiated by direct user action (navigation, clicks)
    AI       — URLs accessed/generated by the model via tool use
    PLATFORM — URLs belonging to infrastructure (CDN, telemetry, APIs)

Attribution is temporal, contextual, metadata-aware, and stream-aware.
Every attribution includes a confidence score (0–100) and evidence text
suitable for DFRWS / academic forensic reporting.

Core forensic pipeline
----------------------
1. url_extractor        — Harvests raw URLs from all HAR layers
2. stream_url_parser    — Deep-parses SSE / event-stream chunks for AI URLs
3. url_normalizer       — Strips tracking params, deduplicates
4. forensic_attributor  — Deterministic heuristic classification
5. timeline_correlator  — Anchors attribution to stream event timestamps
6. confidence_scorer    — Produces 0–100 evidence-based confidence
"""

from __future__ import annotations

import json
import re
import urllib.parse
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set, Tuple

from .helpers import _headers, _resp_text_raw, _path, _ts


# ─────────────────────────────────────────────────────────────────────────────
#  DATA STRUCTURES
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class URLArtifact:
    """Single forensic URL record ready for table output."""
    raw_url:        str
    normalized_url: str
    domain:         str
    attribution:    str          # "HUMAN" | "AI" | "PLATFORM"
    confidence:     int          # 0–100
    evidence:       str          # Human-readable forensic rationale
    har_location:   str          # Where in the HAR this was found
    json_path:      str          # Precise JSON path
    source_type:    str          # "network_request" | "sse_stream" | "metadata"
    trigger:        str          # What triggered this URL (search_start, navigation, etc.)
    timeline_anchor: str         # ISO timestamp or stream event ref
    url_role:       str          # "search_result" | "cited_source" | "cdn_asset" | etc.
    snippet:        str          # Article snippet if available (AI URLs)
    pub_date:       str          # Publication date if available (AI URLs)

    # Canonical artifact fields for table output
    @property
    def artifact(self) -> str:
        return f"url_{self.url_role}"

    @property
    def value(self) -> str:
        return self.normalized_url

    @property
    def reason(self) -> str:
        return self.evidence

    def to_row(self) -> Dict:
        """Convert to standard artifact row dict for existing display/export."""
        return {
            "artifact":     self.artifact,
            "value":        self.normalized_url,
            "har_location": self.har_location,
            "json_path":    self.json_path,
            "attribution":  self.attribution,
            "reason":       self.evidence,
            # Extended URL-specific fields
            "url_raw":      self.raw_url,
            "url_domain":   self.domain,
            "url_confidence": self.confidence,
            "url_trigger":  self.trigger,
            "url_role":     self.url_role,
            "url_snippet":  self.snippet,
            "url_pub_date": self.pub_date,
            "url_timeline": self.timeline_anchor,
            "url_source_type": self.source_type,
        }


@dataclass
class StreamTimeline:
    """
    Records key temporal markers extracted from the SSE stream.
    Used to anchor URL attribution temporally (before/after search_start etc.)
    """
    search_start_seq:    Optional[int]   = None   # SSE seq# of search_start marker
    search_start_ts:     str             = ""
    tool_invoked_seq:    Optional[int]   = None   # SSE seq# of SonicBrowserTool event
    last_token_seq:      Optional[int]   = None
    first_token_seq:     Optional[int]   = None
    favicon_fetch_ts:    str             = ""     # When browser fetched favicons
    search_queries:      List[str]       = field(default_factory=list)
    tool_name:           str             = ""


# ─────────────────────────────────────────────────────────────────────────────
#  DOMAIN / URL CLASSIFICATION RULES
# ─────────────────────────────────────────────────────────────────────────────

# Definitive PLATFORM domains — 100% confidence
_PLATFORM_DOMAINS_EXACT: Set[str] = {
    "chatgpt.com",
    "openai.com",
    "auth.openai.com",
    "cdn.oaistatic.com",
    "browser-intake-datadoghq.com",
    "datadoghq.com",
    "gemini.google.com",
    "gemini.gstatic.com",
    "claude.ai",
    "anthropic.com",
}

# PLATFORM domain suffixes — 95% confidence
_PLATFORM_DOMAIN_SUFFIXES: Tuple[str, ...] = (
    ".oaistatic.com",
    ".openai.com",
    ".chatgpt.com",
    ".datadoghq.com",
    ".anthropic.com",
    ".claude.ai",
)

# PLATFORM path patterns
_PLATFORM_PATH_PATTERNS: List[Tuple[re.Pattern, str]] = [
    (re.compile(r"/cdn/assets/"),                    "CDN static asset bundle"),
    (re.compile(r"/sentinel/"),                      "Sentinel anti-bot infrastructure"),
    (re.compile(r"/ces/v1/"),                        "CES telemetry pipeline"),
    (re.compile(r"/backend-anon/f/conversation"),    "ChatGPT conversation API"),
    (re.compile(r"/backend-api/"),                   "ChatGPT backend API"),
    (re.compile(r"/f/conversation"),                 "ChatGPT conversation stream"),
    (re.compile(r"/lat/r"),                          "Latency reporting telemetry"),
    (re.compile(r"/o11y/v1/traces"),                 "OpenTelemetry RUM traces"),
    (re.compile(r"faviconV2"),                       "gstatic favicon CDN"),
    (re.compile(r"/s2/favicons"),                    "Google favicon proxy"),
    (re.compile(r"signaler-pa\.clients6\.google"),   "Google Signals"),
    (re.compile(r"/BardFrontendService"),            "Gemini BardFrontend API"),
    (re.compile(r"/StreamGenerate"),                 "Gemini StreamGenerate API"),
    (re.compile(r"analytics\.google\.com"),          "Google Analytics"),
    (re.compile(r"googletagmanager\.com"),           "Google Tag Manager"),
    (re.compile(r"play\.google\.com"),               "Google Play CDN"),
    (re.compile(r"fonts\.gstatic\.com"),             "Google Fonts CDN"),
    (re.compile(r"accounts\.google\.com"),           "Google Accounts auth"),
]

# Tracking params to strip during normalization
_TRACKING_PARAMS: Set[str] = {
    "utm_source", "utm_medium", "utm_campaign", "utm_content", "utm_term",
    "gclid", "gbraid", "gad_source", "gad_campaignid", "c_id", "c_agid",
    "c_crid", "c_kwid", "c_ims", "c_pms", "c_nw", "c_dvc",
    "ref", "referrer", "source", "fbclid", "msclkid",
    "srsltid",
}


# ─────────────────────────────────────────────────────────────────────────────
#  1. URL NORMALIZER
# ─────────────────────────────────────────────────────────────────────────────

def normalize_url(raw: str) -> str:
    """
    Strip tracking parameters and chatgpt attribution suffixes.
    Returns a clean, canonical URL for deduplication.
    """
    if not raw or not raw.startswith("http"):
        return raw
    try:
        parsed = urllib.parse.urlparse(raw)
        qs = urllib.parse.parse_qs(parsed.query, keep_blank_values=True)
        # Remove known tracking params
        clean_qs = {k: v for k, v in qs.items() if k not in _TRACKING_PARAMS}
        new_query = urllib.parse.urlencode(clean_qs, doseq=True)
        clean = parsed._replace(query=new_query)
        return urllib.parse.urlunparse(clean)
    except Exception:
        return raw


def extract_domain(url: str) -> str:
    """Extract the registered domain from a URL."""
    try:
        return urllib.parse.urlparse(url).netloc.lower()
    except Exception:
        return ""


# ─────────────────────────────────────────────────────────────────────────────
#  2. SSE / EVENT-STREAM DEEP PARSER
# ─────────────────────────────────────────────────────────────────────────────

def _parse_sse_lines(text: str) -> List[Dict]:
    """
    Parse raw SSE text into a sequence of (seq, data_dict) events.
    Handles both newline-delimited and concatenated-chunk formats.
    """
    events = []
    seq = 0
    for line in text.splitlines():
        s = line.strip()
        if not s.startswith("data:"):
            continue
        raw = s[5:].strip()
        if not raw or raw == "[DONE]":
            continue
        try:
            parsed = json.loads(raw)
            events.append({"seq": seq, "data": parsed})
            seq += 1
        except (json.JSONDecodeError, ValueError):
            pass
    return events


def _walk_patches(v_field) -> List[Dict]:
    """
    Recursively collect all patch objects from the 'v' field of SSE deltas.
    Handles both dict (full message) and list (patch array) variants.
    """
    patches = []
    if isinstance(v_field, dict):
        patches.append(v_field)
    elif isinstance(v_field, list):
        for item in v_field:
            if isinstance(item, dict):
                patches.append(item)
    return patches


def extract_ai_urls_from_sse(sse_text: str, entry_url: str, entry_ts: str,
                               timeline: StreamTimeline) -> List[Dict]:
    """
    Deep-parse an SSE stream to extract all AI-attributed URLs.

    Extracts from:
      - search_result_groups       (raw search index results)
      - content_references patches (cited article content + snippets)
      - sources_footnote           (final citation list shown in UI)
      - url_moderation events      (AI-generated URLs being safety-checked)
      - search_model_queries       (the refined search query used)
      - tether_browsing_display    (Claude/legacy browsing results)

    Returns list of raw URL dicts with context fields.
    """
    results = []
    events = _parse_sse_lines(sse_text)

    for evt in events:
        seq  = evt["seq"]
        data = evt["data"]
        if not isinstance(data, dict):
            continue

        dtype = data.get("type", "")

        # ── message_marker: search_start ─────────────────────────────────
        if dtype == "message_marker":
            marker = data.get("marker", "")
            if marker == "search_start" and timeline.search_start_seq is None:
                timeline.search_start_seq = seq
                timeline.search_start_ts  = entry_ts

        # ── server_ste_metadata: tool name ───────────────────────────────
        if dtype == "server_ste_metadata":
            meta = data.get("metadata", {}) or {}
            if meta.get("tool_name"):
                timeline.tool_name = meta["tool_name"]
            if meta.get("tool_invoked") and timeline.tool_invoked_seq is None:
                timeline.tool_invoked_seq = seq

        # ── search_model_queries ──────────────────────────────────────────
        v = data.get("v", {})
        if isinstance(v, dict):
            msg   = v.get("message", {}) or {}
            meta  = msg.get("metadata", {}) or {}
            content = msg.get("content", {}) or {}
            ctype = content.get("content_type", "")

            # search_model_queries  → reveals refined search query
            smq = meta.get("search_model_queries")
            if smq and isinstance(smq, dict):
                for q in smq.get("queries", []):
                    if q and q not in timeline.search_queries:
                        timeline.search_queries.append(q)

            # search_result_groups → raw search index results
            srg = meta.get("search_result_groups")
            if srg and isinstance(srg, list):
                for group in srg:
                    domain = group.get("domain", "")
                    for entry in group.get("entries", []):
                        url = entry.get("url", "")
                        if url:
                            results.append({
                                "url":        url,
                                "url_role":   "search_result",
                                "source":     "search_result_groups",
                                "domain":     domain or extract_domain(url),
                                "title":      entry.get("title", ""),
                                "snippet":    entry.get("snippet", ""),
                                "pub_date":   "",
                                "result_src": entry.get("result_source", ""),
                                "seq":        seq,
                                "entry_url":  entry_url,
                                "entry_ts":   entry_ts,
                            })

            # content_references → cited articles with full snippets
            refs = meta.get("content_references")
            if refs and isinstance(refs, list):
                for ref in refs:
                    if not isinstance(ref, dict):
                        continue
                    ref_type = ref.get("type", "")

                    # sources_footnote → final citation list
                    if ref_type == "sources_footnote":
                        for src in ref.get("sources", []):
                            url = src.get("url", "")
                            if url:
                                results.append({
                                    "url":      url,
                                    "url_role": "cited_source",
                                    "source":   "sources_footnote",
                                    "domain":   src.get("attribution", extract_domain(url)),
                                    "title":    src.get("title", ""),
                                    "snippet":  "",
                                    "pub_date": "",
                                    "result_src": "",
                                    "seq":      seq,
                                    "entry_url": entry_url,
                                    "entry_ts":  entry_ts,
                                })

                    # grouped_webpages → full article content ChatGPT read
                    if ref_type == "grouped_webpages" or "items" in ref:
                        for item in ref.get("items", []):
                            url = item.get("url", "")
                            if url:
                                pub_raw = item.get("pub_date")
                                try:
                                    from datetime import datetime
                                    pub_str = datetime.utcfromtimestamp(pub_raw).strftime(
                                        "%Y-%m-%d") if pub_raw else ""
                                except Exception:
                                    pub_str = str(pub_raw) if pub_raw else ""
                                results.append({
                                    "url":      url,
                                    "url_role": "retrieved_content",
                                    "source":   "content_references_grouped_webpages",
                                    "domain":   item.get("attribution", extract_domain(url)),
                                    "title":    item.get("title", ""),
                                    "snippet":  item.get("snippet", "")[:400],
                                    "pub_date": pub_str,
                                    "result_src": item.get("result_source", ""),
                                    "seq":      seq,
                                    "entry_url": entry_url,
                                    "entry_ts":  entry_ts,
                                })
                            # Supporting websites within an item
                            for sw in item.get("supporting_websites", []):
                                sw_url = sw.get("url", "")
                                if sw_url:
                                    results.append({
                                        "url":      sw_url,
                                        "url_role": "supporting_source",
                                        "source":   "content_references_supporting_websites",
                                        "domain":   sw.get("attribution", extract_domain(sw_url)),
                                        "title":    sw.get("title", ""),
                                        "snippet":  "",
                                        "pub_date": "",
                                        "result_src": sw.get("result_source", ""),
                                        "seq":      seq,
                                        "entry_url": entry_url,
                                        "entry_ts":  entry_ts,
                                    })

            # safe_urls inside content_references patches
            for patch in _walk_patches(v):
                p_key = str(patch.get("p", ""))
                p_val = patch.get("v")
                if "content_references" in p_key and isinstance(p_val, list):
                    for url in p_val:
                        if isinstance(url, str) and url.startswith("http"):
                            results.append({
                                "url":      url,
                                "url_role": "citation_patch_url",
                                "source":   "content_references_patch",
                                "domain":   extract_domain(url),
                                "title":    "",
                                "snippet":  "",
                                "pub_date": "",
                                "result_src": "",
                                "seq":      seq,
                                "entry_url": entry_url,
                                "entry_ts":  entry_ts,
                            })

            # tether_browsing_display (Claude / legacy ChatGPT browsing)
            if ctype == "tether_browsing_display":
                for part in content.get("result", {}).get("parts", []):
                    if isinstance(part, dict):
                        url = part.get("url", "")
                        if url:
                            results.append({
                                "url":      url,
                                "url_role": "browsing_result",
                                "source":   "tether_browsing_display",
                                "domain":   extract_domain(url),
                                "title":    part.get("title", ""),
                                "snippet":  part.get("snippet", ""),
                                "pub_date": "",
                                "result_src": "tether",
                                "seq":      seq,
                                "entry_url": entry_url,
                                "entry_ts":  entry_ts,
                            })

            # code content_type: SonicBrowserTool / search() call
            if ctype == "code":
                code_text = content.get("text", "")
                urls_in_code = re.findall(r'https?://[^\s\'"<>]+', code_text)
                for url in urls_in_code:
                    results.append({
                        "url":      url,
                        "url_role": "tool_call_url",
                        "source":   "sse_code_block",
                        "domain":   extract_domain(url),
                        "title":    "",
                        "snippet":  "",
                        "pub_date": "",
                        "result_src": "",
                        "seq":      seq,
                        "entry_url": entry_url,
                        "entry_ts":  entry_ts,
                    })

        # ── Patch-array format (list v field) ─────────────────────────────
        if isinstance(v, list):
            for patch in v:
                if not isinstance(patch, dict):
                    continue
                pval = patch.get("v")
                pkey = str(patch.get("p", ""))

                # Inline safe_urls arrays
                if isinstance(pval, list):
                    for item in pval:
                        if isinstance(item, str) and item.startswith("http"):
                            role = "citation_patch_url"
                            if "search_result" in pkey:
                                role = "search_result"
                            results.append({
                                "url":      item,
                                "url_role": role,
                                "source":   f"patch:{pkey[:60]}",
                                "domain":   extract_domain(item),
                                "title":    "",
                                "snippet":  "",
                                "pub_date": "",
                                "result_src": "",
                                "seq":      seq,
                                "entry_url": entry_url,
                                "entry_ts":  entry_ts,
                            })

                # Patch value is a dict (grouped_webpages embedded in patch)
                if isinstance(pval, dict):
                    for item in pval.get("items", []):
                        if not isinstance(item, dict):
                            continue
                        url = item.get("url", "")
                        if url and url.startswith("http"):
                            pub_raw = item.get("pub_date")
                            try:
                                from datetime import datetime
                                pub_str = datetime.utcfromtimestamp(pub_raw).strftime(
                                    "%Y-%m-%d") if pub_raw else ""
                            except Exception:
                                pub_str = str(pub_raw) if pub_raw else ""
                            results.append({
                                "url":      url,
                                "url_role": "retrieved_content",
                                "source":   f"patch_items:{pkey[:40]}",
                                "domain":   item.get("attribution", extract_domain(url)),
                                "title":    item.get("title", ""),
                                "snippet":  item.get("snippet", "")[:400],
                                "pub_date": pub_str,
                                "result_src": item.get("result_source", ""),
                                "seq":      seq,
                                "entry_url": entry_url,
                                "entry_ts":  entry_ts,
                            })

    return results


# ─────────────────────────────────────────────────────────────────────────────
#  3. NETWORK REQUEST URL EXTRACTOR
# ─────────────────────────────────────────────────────────────────────────────

def extract_network_urls(entries: List[Dict]) -> List[Dict]:
    """
    Extract URLs from direct network requests.
    Classifies initiator type and resource type for HUMAN vs PLATFORM heuristics.
    """
    results = []
    for i, entry in enumerate(entries):
        req    = entry.get("request", {})
        url    = req.get("url", "")
        method = req.get("method", "GET")
        ts     = entry.get("startedDateTime", "")
        # HAR initiator (Chrome DevTools)
        initiator = entry.get("_initiator", {}) or {}
        init_type = initiator.get("type", "")  # "navigation" | "script" | "other"
        resource_type = entry.get("_resourceType", "")  # "document" | "xhr" | "fetch" etc.
        referer   = ""
        for h in req.get("headers", []):
            if h.get("name", "").lower() == "referer":
                referer = h.get("value", "")
                break

        results.append({
            "url":           url,
            "method":        method,
            "entry_index":   i,
            "ts":            ts,
            "initiator_type": init_type,
            "resource_type": resource_type,
            "referer":       referer,
            "source":        "network_request",
        })
    return results


# ─────────────────────────────────────────────────────────────────────────────
#  4. FORENSIC ATTRIBUTOR
# ─────────────────────────────────────────────────────────────────────────────

def _is_platform_domain(domain: str) -> Tuple[bool, int, str]:
    """
    Returns (is_platform, confidence, reason).
    """
    d = domain.lower()

    if d in _PLATFORM_DOMAINS_EXACT:
        return True, 100, f"Domain '{d}' is a confirmed OpenAI/Anthropic/Google AI platform domain."

    for suffix in _PLATFORM_DOMAIN_SUFFIXES:
        if d.endswith(suffix):
            return True, 95, f"Domain ends with platform infrastructure suffix '{suffix}'."

    # gstatic / google infra
    if d.endswith(".gstatic.com") or d.endswith(".google.com") or d == "www.google.com":
        return True, 90, f"Domain '{d}' is Google CDN/infrastructure (gstatic/google.com)."

    # Datadog and monitoring
    if "datadoghq" in d or "datadog" in d:
        return True, 98, f"Domain '{d}' is Datadog monitoring infrastructure."

    # Analytics
    if "google-analytics" in d or "googletagmanager" in d:
        return True, 95, f"Domain '{d}' is Google Analytics/Tag Manager infrastructure."

    return False, 0, ""


def _classify_platform_path(url: str) -> Tuple[bool, int, str]:
    """Check URL path against known platform patterns."""
    for pattern, description in _PLATFORM_PATH_PATTERNS:
        if pattern.search(url):
            return True, 97, f"URL path matches platform pattern: {description}."
    return False, 0, ""


def _build_platform_evidence(url: str, domain: str, path_desc: str,
                               domain_reason: str, confidence: int) -> str:
    return (
        f"PLATFORM: This URL belongs to AI platform infrastructure. "
        f"{domain_reason or path_desc} "
        f"The AI model does not generate infrastructure requests; users do not "
        f"manually navigate to these endpoints. The platform's systems "
        f"(telemetry, CDN, authentication, anti-bot) make these requests "
        f"automatically as part of service operation. "
        f"Confidence: {confidence}%."
    )


def _build_ai_evidence(url: str, domain: str, url_role: str, source: str,
                        trigger: str, tool_name: str, search_queries: List[str],
                        snippet: str, confidence: int) -> str:
    role_desc = {
        "search_result":      "a raw search index result returned by the AI's search tool",
        "cited_source":       "a citation included in the AI's generated response",
        "retrieved_content":  "a page whose full content was retrieved and read by the AI",
        "supporting_source":  "a supporting reference linked by the AI's cited source",
        "citation_patch_url": "a URL resolved during AI citation patch generation",
        "browsing_result":    "a page returned by the AI's browsing tool",
        "tool_call_url":      "a URL embedded in the AI's tool invocation code",
    }.get(url_role, "an AI-accessed resource")

    query_ctx = ""
    if search_queries:
        query_ctx = f" The model searched for: \"{search_queries[0]}\". "

    trigger_ctx = ""
    if trigger:
        trigger_ctx = f" This URL appeared after the '{trigger}' event in the SSE stream,"
        trigger_ctx += " confirming it was generated during AI tool execution, not user navigation."

    snippet_ctx = ""
    if snippet:
        truncated = snippet[:120] + ("…" if len(snippet) > 120 else "")
        snippet_ctx = f" The AI read content including: \"{truncated}\""

    return (
        f"AI: URL identified as {role_desc}. "
        f"Found inside '{source}' in the SSE event stream.{query_ctx}"
        f"{trigger_ctx}{snippet_ctx} "
        f"The tool '{tool_name or 'SonicBrowserTool'}' accessed this resource on behalf of the model. "
        f"This URL does not appear as a direct browser network request — "
        f"it exists only within the streamed assistant metadata, "
        f"proving server-side AI retrieval. "
        f"Confidence: {confidence}%."
    )


def _build_human_evidence(url: str, domain: str, initiator_type: str,
                           resource_type: str, referer: str, confidence: int) -> str:
    init_ctx = ""
    if initiator_type == "navigation":
        init_ctx = " HAR initiator type is 'navigation', confirming direct browser navigation."
    if resource_type == "document":
        init_ctx += " Resource type is 'document', indicating a top-level page load."
    if referer and "chatgpt.com" not in referer and "openai.com" not in referer:
        init_ctx += f" Referer header shows user navigated from '{referer[:60]}'."

    return (
        f"HUMAN: URL initiated by direct user browser action. "
        f"{init_ctx} "
        f"This request occurred before or independently of any AI tool invocation. "
        f"The domain '{domain}' is not part of platform infrastructure. "
        f"Pattern consistent with manual browsing or user-clicked link. "
        f"Confidence: {confidence}%."
    )


# ─────────────────────────────────────────────────────────────────────────────
#  5. FAVICON ATTRIBUTION
# ─────────────────────────────────────────────────────────────────────────────

def classify_favicon_request(url: str, ts: str, timeline: StreamTimeline) -> URLArtifact:
    """
    Favicon fetches are a critical forensic bridge:
    - The domain in the favicon URL reveals which AI-cited sources were used
    - The timing (after last_token) confirms they're triggered by citation rendering
    - Attribution: PLATFORM (the platform's UI fetches them, not the AI or user)
    """
    # Extract the target domain from favicon URL query params
    cited_domain = ""
    for param in ["domain", "url"]:
        m = re.search(rf"[?&]{param}=([^&]+)", url)
        if m:
            cited_domain = urllib.parse.unquote(m.group(1))
            cited_domain = extract_domain(cited_domain) if cited_domain.startswith("http") else cited_domain
            break

    evidence = (
        f"PLATFORM: Favicon fetch request to Google's favicon CDN service. "
        f"The URL reveals that the AI cited a source from '{cited_domain}'. "
        f"These requests are made automatically by the ChatGPT frontend UI "
        f"to render the small site icons shown next to each citation link. "
        f"Timing after the SSE stream completes confirms this is UI rendering "
        f"triggered by AI-generated citations, not user navigation. "
        f"Attribution is PLATFORM because the platform's frontend code "
        f"initiates these requests, though they are forensic evidence of AI URL activity. "
        f"Confidence: 98%."
    )

    return URLArtifact(
        raw_url=url,
        normalized_url=normalize_url(url),
        domain=extract_domain(url),
        attribution="PLATFORM",
        confidence=98,
        evidence=evidence,
        har_location=f"GET {url[:80]}... (favicon CDN)",
        json_path="log.entries[].request.url (gstatic/google favicon)",
        source_type="network_request",
        trigger="citation_render",
        timeline_anchor=ts,
        url_role="favicon_cdn",
        snippet=f"Reveals AI cited domain: {cited_domain}",
        pub_date="",
    )


# ─────────────────────────────────────────────────────────────────────────────
#  6. MAIN ATTRIBUTION ENGINE
# ─────────────────────────────────────────────────────────────────────────────

def attribute_url(raw_url: str, context: Dict, timeline: StreamTimeline) -> URLArtifact:
    """
    Core deterministic heuristic classifier for a single URL.

    Decision order (short-circuit on first match):
      1. Empty / non-HTTP  → skip
      2. Favicon requests  → PLATFORM (with cited domain extraction)
      3. Known platform domain / path → PLATFORM
      4. AI source (from SSE stream metadata) → AI
      5. Network request before search_start → lean HUMAN
      6. Network request with navigation initiator → HUMAN
      7. Default → PLATFORM (conservative)
    """
    url      = raw_url.strip()
    domain   = extract_domain(url)
    source   = context.get("source", "")
    url_role = context.get("url_role", "unknown")
    ts       = context.get("entry_ts", context.get("ts", ""))
    seq      = context.get("seq")

    # ── Favicon ──────────────────────────────────────────────────────────
    if "faviconV2" in url or "/s2/favicons" in url:
        return classify_favicon_request(url, ts, timeline)

    # ── Platform domain check ─────────────────────────────────────────────
    is_plat_domain, plat_conf, plat_reason = _is_platform_domain(domain)
    is_plat_path,   path_conf, path_desc   = _classify_platform_path(url)

    if is_plat_domain or is_plat_path:
        confidence = max(plat_conf, path_conf)
        evidence   = _build_platform_evidence(
            url, domain, path_desc, plat_reason, confidence
        )
        path_part = _path(url)

        # Determine specific role
        if "sentinel" in url:
            role = "sentinel_endpoint"
        elif "cdn" in url or ".js" in path_part or ".css" in path_part or ".svg" in path_part:
            role = "cdn_asset"
        elif "telemetry" in url or "ces/v1" in url or "datadoghq" in url:
            role = "telemetry"
        elif "conversation" in url:
            role = "conversation_api"
        elif "favicon" in url:
            role = "favicon_cdn"
        elif "analytics" in url or "tagmanager" in url:
            role = "analytics"
        elif "auth" in url or "accounts" in url:
            role = "auth_endpoint"
        else:
            role = "platform_api"

        return URLArtifact(
            raw_url=raw_url,
            normalized_url=normalize_url(url),
            domain=domain,
            attribution="PLATFORM",
            confidence=confidence,
            evidence=evidence,
            har_location=context.get("har_location",
                         f"{context.get('method','GET')} {_path(url)} [{source}]"),
            json_path=context.get("json_path", f"log.entries[{context.get('entry_index','')}].request.url"),
            source_type=context.get("source_type", "network_request"),
            trigger="platform_infrastructure",
            timeline_anchor=ts,
            url_role=role,
            snippet="",
            pub_date="",
        )

    # ── AI source (from SSE stream) ───────────────────────────────────────
    if source in (
        "search_result_groups",
        "sources_footnote",
        "content_references_grouped_webpages",
        "content_references_supporting_websites",
        "content_references_patch",
        "tether_browsing_display",
        "sse_code_block",
    ) or source.startswith("patch"):

        # Confidence varies by source
        conf_map = {
            "search_result_groups":                  90,
            "sources_footnote":                      97,
            "content_references_grouped_webpages":   95,
            "content_references_supporting_websites": 88,
            "content_references_patch":              85,
            "tether_browsing_display":               95,
            "sse_code_block":                        92,
        }
        confidence = conf_map.get(source, 85)

        # Higher confidence if after search_start
        trigger = ""
        if (timeline.search_start_seq is not None and
                seq is not None and seq > timeline.search_start_seq):
            confidence = min(confidence + 3, 99)
            trigger = "search_start"

        evidence = _build_ai_evidence(
            url=url,
            domain=domain,
            url_role=url_role,
            source=source,
            trigger=trigger,
            tool_name=timeline.tool_name,
            search_queries=timeline.search_queries,
            snippet=context.get("snippet", ""),
            confidence=confidence,
        )

        return URLArtifact(
            raw_url=raw_url,
            normalized_url=normalize_url(url),
            domain=domain,
            attribution="AI",
            confidence=confidence,
            evidence=evidence,
            har_location=(
                f"SSE stream: {source} "
                f"(seq={seq}, entry={context.get('entry_url','')[:50]})"
            ),
            json_path=(
                f"SSE delta.v.message.metadata.{source}"
                if "patch" not in source else
                f"SSE delta.v[].p contains {source}"
            ),
            source_type="sse_stream",
            trigger=trigger or "tool_execution",
            timeline_anchor=ts,
            url_role=url_role,
            snippet=context.get("snippet", ""),
            pub_date=context.get("pub_date", ""),
        )

    # ── Network request — HUMAN vs PLATFORM disambiguation ────────────────
    initiator_type = context.get("initiator_type", "")
    resource_type  = context.get("resource_type", "")
    referer        = context.get("referer", "")
    method         = context.get("method", "GET")
    entry_index    = context.get("entry_index", 0)

    # Navigation-initiated top-level document → strong HUMAN signal
    if initiator_type == "navigation" or resource_type == "document":
        confidence = 80
        evidence   = _build_human_evidence(
            url, domain, initiator_type, resource_type, referer, confidence
        )
        return URLArtifact(
            raw_url=raw_url,
            normalized_url=normalize_url(url),
            domain=domain,
            attribution="HUMAN",
            confidence=confidence,
            evidence=evidence,
            har_location=f"[{entry_index}] {method} {_path(url)}",
            json_path=f"log.entries[{entry_index}].request.url",
            source_type="network_request",
            trigger="user_navigation",
            timeline_anchor=ts,
            url_role="user_navigation",
            snippet="",
            pub_date="",
        )

    # Default: conservative PLATFORM (most unexplained requests in a ChatGPT
    # session are platform-initiated scripts / XHR background calls)
    evidence = (
        f"PLATFORM (default): URL '{domain}' could not be definitively attributed "
        f"to user navigation or AI tool use. In a ChatGPT session, most background "
        f"XHR/fetch requests to non-third-party domains are platform-initiated. "
        f"Confidence: 60% (low — consider manual review)."
    )
    return URLArtifact(
        raw_url=raw_url,
        normalized_url=normalize_url(url),
        domain=domain,
        attribution="PLATFORM",
        confidence=60,
        evidence=evidence,
        har_location=f"[{entry_index}] {method} {_path(url)}",
        json_path=f"log.entries[{entry_index}].request.url",
        source_type="network_request",
        trigger="platform_background",
        timeline_anchor=ts,
        url_role="platform_background",
        snippet="",
        pub_date="",
    )


# ─────────────────────────────────────────────────────────────────────────────
#  7. DEDUPLICATION
# ─────────────────────────────────────────────────────────────────────────────

def deduplicate_artifacts(artifacts: List[URLArtifact]) -> List[URLArtifact]:
    """
    Deduplicate by normalized URL, keeping highest-confidence record.
    AI attribution always wins over PLATFORM for same URL.
    """
    seen: Dict[str, URLArtifact] = {}
    for a in artifacts:
        key = a.normalized_url
        if key not in seen:
            seen[key] = a
        else:
            existing = seen[key]
            # AI > HUMAN > PLATFORM in priority
            priority = {"AI": 3, "HUMAN": 2, "PLATFORM": 1}
            if priority.get(a.attribution, 0) > priority.get(existing.attribution, 0):
                seen[key] = a
            elif (priority.get(a.attribution, 0) == priority.get(existing.attribution, 0)
                  and a.confidence > existing.confidence):
                seen[key] = a
    return list(seen.values())


# ─────────────────────────────────────────────────────────────────────────────
#  8. RELATIONSHIP MAP BUILDER
# ─────────────────────────────────────────────────────────────────────────────

def build_url_relationship_map(artifacts: List[URLArtifact],
                                 timeline: StreamTimeline) -> List[Dict]:
    """
    Reconstructs the full retrieval chain:
      User Query → search_model_queries → search_result_groups
                → content_references (retrieved_content)
                → sources_footnote (cited_source)
                → favicon_cdn (UI rendering)

    Returns a list of relationship records for export.
    """
    chain = []

    # Layer 0: Search queries
    for q in timeline.search_queries:
        chain.append({
            "layer":       0,
            "layer_name":  "Search Query",
            "value":       q,
            "attribution": "AI",
            "description": "Refined query generated by AI and sent to search engine",
        })

    # Layer 1: Raw search results
    for a in artifacts:
        if a.url_role == "search_result":
            chain.append({
                "layer":       1,
                "layer_name":  "Search Result (Raw)",
                "value":       a.normalized_url,
                "domain":      a.domain,
                "attribution": "AI",
                "description": "Raw search index result returned to AI (may not be cited)",
            })

    # Layer 2: Retrieved content
    for a in artifacts:
        if a.url_role == "retrieved_content":
            chain.append({
                "layer":       2,
                "layer_name":  "Retrieved Content",
                "value":       a.normalized_url,
                "domain":      a.domain,
                "attribution": "AI",
                "description": f"Full page content read by AI: {a.title[:60] if hasattr(a,'title') else ''}",
            })

    # Layer 3: Cited sources
    for a in artifacts:
        if a.url_role == "cited_source":
            chain.append({
                "layer":       3,
                "layer_name":  "Cited Source (Final)",
                "value":       a.normalized_url,
                "domain":      a.domain,
                "attribution": "AI",
                "description": "Source cited in AI response visible to user",
            })

    # Layer 4: Favicon fetches (UI proof)
    for a in artifacts:
        if a.url_role == "favicon_cdn":
            chain.append({
                "layer":       4,
                "layer_name":  "Favicon Fetch (UI Proof)",
                "value":       a.normalized_url,
                "domain":      a.domain,
                "attribution": "PLATFORM",
                "description": f"Browser fetched favicon for cited domain. Evidence: {a.snippet}",
            })

    return chain


# ─────────────────────────────────────────────────────────────────────────────
#  9. TOP-LEVEL ORCHESTRATOR
# ─────────────────────────────────────────────────────────────────────────────

def run_url_attribution(entries: List[Dict]) -> Tuple[List[URLArtifact], StreamTimeline, List[Dict]]:
    """
    Full URL forensic attribution pipeline.

    Parameters
    ----------
    entries : HAR log entries

    Returns
    -------
    (url_artifacts, timeline, relationship_chain)
    """
    timeline   = StreamTimeline()
    raw_urls: List[Dict] = []

    # Pass 1: Extract AI URLs from SSE streams
    for entry in entries:
        content   = entry["response"]["content"]
        mime      = content.get("mimeType", "")
        entry_url = entry["request"]["url"]
        entry_ts  = entry.get("startedDateTime", "")

        if "event-stream" in mime or "text/plain" in mime:
            text = _resp_text_raw(entry)
            if text:
                ai_urls = extract_ai_urls_from_sse(text, entry_url, entry_ts, timeline)
                raw_urls.extend(ai_urls)

    # Pass 2: Extract network request URLs
    net_urls = extract_network_urls(entries)
    raw_urls.extend(net_urls)

    # Pass 3: Attribute each URL
    artifacts: List[URLArtifact] = []
    for url_ctx in raw_urls:
        raw = url_ctx.get("url", "")
        if not raw or not raw.startswith("http"):
            continue
        artifact = attribute_url(raw, url_ctx, timeline)
        artifacts.append(artifact)

    # Pass 4: Deduplicate
    artifacts = deduplicate_artifacts(artifacts)

    # Pass 5: Sort — AI first (most forensically interesting), then HUMAN, then PLATFORM
    priority = {"AI": 0, "HUMAN": 1, "PLATFORM": 2}
    artifacts.sort(key=lambda a: (priority.get(a.attribution, 9), -a.confidence))

    # Pass 6: Build relationship map
    chain = build_url_relationship_map(artifacts, timeline)

    return artifacts, timeline, chain
